import requests
from datetime import datetime, timedelta
import re

OPEN_METEO_FORECAST = "https://api.open-meteo.com/v1/forecast"
OPEN_METEO_ARCHIVE = "https://archive-api.open-meteo.com/v1/archive"

# Default testing coordinates for Chennai
DEFAULT_LAT = 13.0827
DEFAULT_LON = 80.2707


def _ensure_datetime(d):
    """Ensure d is a full datetime object, not just a date."""
    if d is None:
        return None
    if isinstance(d, datetime):
        return d
    return datetime(d.year, d.month, d.day)


def _infer_past_date_from_query(query: str):
    """
    Fallback: if query contains an explicit past year (e.g. 2025),
    resolve to today's month/day in that year.
    Returns a datetime or None.
    """
    current_year = datetime.now().year
    m = re.search(r'\b(19\d{2}|20\d{2})\b', query.lower())
    if m:
        year = int(m.group(1))
        if year < current_year:
            now = datetime.now()
            try:
                return datetime(year, now.month, now.day)
            except ValueError:
                return datetime(year, now.month, 28)
    return None


def _extract_all_past_years(query: str):
    """
    Extract ALL past years mentioned in a query, including ranges (e.g., 2021 to 2025).
    Returns a list of datetime objects for each past year found, using today's month/day.
    Used by the comparison route to fetch multiple historical datasets.
    """
    current_year = datetime.now().year
    now = datetime.now()
    q = query.lower()
    
    seen = set()
    years_to_process = []

    # First, detect explicit ranges like "2021 to 2025" or "2021-2025"
    range_matches = re.finditer(r'\b(19\d{2}|20\d{2})\s*(?:to|-|and)\s*(19\d{2}|20\d{2})\b', q)
    for m in range_matches:
        start_y = int(m.group(1))
        end_y = int(m.group(2))
        if start_y > end_y:
            start_y, end_y = end_y, start_y
        for y in range(start_y, end_y + 1):
            if y < current_year and y not in seen:
                seen.add(y)
                years_to_process.append(y)

    # Then detect individual years, ensuring we don't duplicate
    single_matches = re.finditer(r'\b(19\d{2}|20\d{2})\b', q)
    for m in single_matches:
        y = int(m.group(1))
        if y < current_year and y not in seen:
            seen.add(y)
            years_to_process.append(y)
            
    # Cap at max 6 years to avoid blowing up the API / LLM context
    # Sort them descending, take top 6, then sort ascending for chronological order
    years_to_process = sorted(years_to_process, reverse=True)[:6]
    years_to_process.sort()

    past_dates = []
    for year in years_to_process:
        try:
            past_dates.append(datetime(year, now.month, now.day))
        except ValueError:
            past_dates.append(datetime(year, now.month, 28))
            
    return past_dates


def execute_plan(plan):
    """
    Executes the deterministic plan generated by the Planner.
    Routes to the correct external APIs or internal ML modules.
    """
    intent = plan.get("intent", "weather")
    target_date = _ensure_datetime(plan.get("date"))
    ctx = plan.get("context", {})
    query = plan.get("query", "")

    # Fallback: if no date was parsed but a past year exists in the query,
    # infer the date so the Archive API gets triggered correctly.
    # Skip this for comparisons — handled separately below.
    if target_date is None and intent in ["weather_history", "weather"]:
        inferred = _infer_past_date_from_query(query)
        if inferred:
            target_date = inferred
            intent = "weather_history"
            plan["intent"] = intent

    # This dictionary will hold the raw execution results
    execution_result = {
        "weather": None,
        "forecast": None,
        "historical_weather": None,
        "historical_comparison": None,   # stores list of historical datasets for comparison
        "cyclone": None,
        "earthquake": None,
        "tsunami": None,
        "models": None
    }

    try:
        from main import (get_cyclones, get_earthquakes, get_tsunamis,
                          get_weather, get_forecast, fetch_historical_weather)

        now = datetime.utcnow().date()

        # COMPARISON ROUTE
        # When intent is weather_comparison, fetch BOTH current weather AND
        # historical data for every past year mentioned in the query.
        if intent == "weather_comparison" or ctx.get("wants_comparison"):
            # Always fetch current weather for the "present" side of the comparison
            execution_result["weather"] = get_weather()

            # Find all past years mentioned (e.g. 2025, 2024)
            past_dates = _extract_all_past_years(query)

            if past_dates:
                comparison_results = []
                for past_dt in past_dates:
                    past_date_only = past_dt.date()
                    # Only fetch if it's past the archive lag window (~5 days)
                    archive_limit = datetime.utcnow().date() - timedelta(days=5)
                    if past_date_only <= archive_limit:
                        hist = fetch_historical_weather(past_dt, days_range=1)
                        if hist and "error" not in hist:
                            hist["queried_year"] = past_dt.year
                            hist["queried_date"] = past_dt.strftime("%Y-%m-%d")
                            comparison_results.append(hist)

                if comparison_results:
                    execution_result["historical_comparison"] = comparison_results
                    # Also set historical_weather to the first result for
                    # backward-compatibility with the Groq synthesis prompt
                    execution_result["historical_weather"] = comparison_results[0]

            # Also grab forecast for a fuller picture
            execution_result["forecast"] = get_forecast()

        # STANDARD WEATHER / HISTORY / PREDICTION ROUTE
        elif intent in ["weather_history", "weather", "prediction"]:
            if target_date:
                target_date_only = target_date.date() if isinstance(target_date, datetime) else target_date
                if target_date_only < now:
                    execution_result["historical_weather"] = fetch_historical_weather(target_date, days_range=1)
                elif target_date_only > now and (target_date_only - now).days <= 7:
                    execution_result["forecast"] = get_forecast()

            # Current weather: fetch when no specific past date, or today, or general weather
            target_date_only = target_date.date() if target_date and isinstance(target_date, datetime) else target_date
            if not target_date or target_date_only == now:
                execution_result["weather"] = get_weather()

            # General overview: also fetch forecast when no date given
            if not target_date and intent in ["weather", "prediction"]:
                execution_result["forecast"] = get_forecast()

        # CYCLONE ROUTE
        if "cyclone" in plan.get("all_intents", []):
            cy_name = ctx.get("cyclone_name")
            cy_year = ctx.get("year")
            c_data = get_cyclones(name=cy_name, year=cy_year)
            if ctx.get("wants_recent") and not cy_name:
                cyc_list = sorted(c_data.get("cyclones", []), key=lambda c: c["year"], reverse=True)[:3]
                c_data["cyclones"] = cyc_list
            execution_result["cyclone"] = c_data

        # EARTHQUAKE ROUTE
        if "earthquake" in plan.get("all_intents", []):
            execution_result["earthquake"] = get_earthquakes()

        # TSUNAMI ROUTE
        if "tsunami" in plan.get("all_intents", []):
            execution_result["tsunami"] = get_tsunamis()

    except ImportError as e:
        print(f"Executor Import Error: {e}")

    return execution_result